# This workflow will run tests for npm and java

name: checks

on:
  push:
    branches:
    - master
    - production
  pull_request:
    branches:
    - master
    - production

jobs:
  test-front-end:
    runs-on: ubuntu-latest
    steps:
      - name: "checking out"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "setting up npm"
        uses: actions/setup-node@v2
        with:
            node-version: '12.x'

      ############
      # CACHING
      ##########
      - name: "cache node modules"
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      ###############
      # NPM CHECKS
      #############
      - name: npm install
        run: npm install

      - name: ESlint
        run: npm run lint

      - name: Unit Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checking out"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      ###########
      # SET UP
      #########
      - name: "setting up Java"
        uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: "setting up npm"
        uses: actions/setup-node@v2
        with:
            node-version: '12.x'

      ############
      # CACHING
      ##########
      - name: "cache node modules"
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "cache maven dependencies"
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: mapstore-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mapstore-${{ runner.os }}-maven-

      ###############
      # NPM CHECKS
      #############
      - name: npm install
        run: npm install

      - name: compile
        run: npm run compile
      ################
      # JAVA CHECKS
      ##############
      - name: java
        run: mvn --batch-mode --update-snapshots verify


